name: elastic-beanstalk-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - if: steps.yarn-cache.outputs.cache-hit == 'true'
        run: echo "yarn cache hit!"
      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: echo "yarn cache missed!"

      - run: yarn install --immutable --immutable-cache --check-cache

      - run: yarn build

      - name: Generate zip File
        run: |
          mv ./ecosystem.config.js .next/standalone
          cd .next/standalone
          zip -r deploy.zip . 
          mv deploy.zip ../../

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: test-app
          environment_name: Testapp-env
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
